# All available Hugo versions are listed here:
# https://gitlab.com/pages/hugo/container_registry
image: registry.gitlab.com/pages/hugo/hugo:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  script:
  - hugo
  except:
  - master

pages:
  script:
  - hugo
  - gzip -k -6 public/
  - gzip -k -6 public/about
  - gzip -k -6 public/categories
  - gzip -k -6 public/css
  - gzip -k -6 public/fonts
  - gzip -k -6 public/tags
  artifacts:
    paths:
    - public
  only:
  - master
