# All available Hugo versions are listed here:
# https://gitlab.com/pages/hugo/container_registry
image: registry.gitlab.com/oct8l/oct8l.gitlab.io/hugo/minify:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  script:
  - hugo
  except:
  - master

pages:
  script:
  - mkdir .public
  - hugo -d .public
  - ls -l
  - ls -l .public
  - minify-json .public
  - find .public -iname *[^min].css | xargs -I {} uglifycss --output {} {}
  - find .public -iname *[^min].js | xargs -I {} uglifyjs -o {} {}
  - find .public -iname *[^min].html | xargs -I {} html-minifier --collapse-whitespace -o {} {}
  - find .public -iname *[^min].png | xargs -I {} imagemin-inplace -o {} {}
  - find .public -iname *[^min].svg | xargs -I {} imagemin-inplace -o {} {}
  - find .public -iname *[^min].jpg | xargs -I {} imagemin-inplace -o {} {}
  - find .public -iname *[^min].jpeg | xargs -I {} imagemin-inplace -o {} {}
  - mv .public public
  - ls -l public
  - ls -l
  artifacts:
    paths:
    - public
  only:
  - master
