# All available Hugo versions are listed here:
# https://gitlab.com/pages/hugo/container_registry
image: registry.gitlab.com/oct8l/oct8l.gitlab.io/hugo/minify:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  script:
  - hugo
  except:
  - master

pages:
  script:
  - hugo && gzip -k -6 $(find public -type f)
  artifacts:
    paths:
    - public
  only:
  - master
