# All available Hugo versions are listed here:
# https://gitlab.com/pages/hugo/container_registry
image: registry.gitlab.com/oct8l/oct8l.gitlab.io/hugo/minify:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  script:
  - hugo
  except:
  - master

pages:
  script:
  - mkdir build
  - hugo -d build
  - ls -l
  - ls -l build
  - find build -iname *.css | xargs -I {} uglifycss --output {} {}
  - find build -iname *.js | xargs -I {} uglifyjs -o {} {}
  - find build -iname *.html | xargs -I {} html-minifier --collapse-whitespace -o {} {}
  - find build -type f | xargs -I {} gzip -k -9 {}
  - mv build public
  - ls -l public
  - ls -l
  artifacts:
    paths:
    - public
  only:
  - master
