baseurl                  = "https://mgrah.am/"
languageCode             = "en-gb"
title                    = "Mike Graham"
theme                    = "sam"

[params]
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    description          = "MGRAH.AM is the website of Mike Graham."
    favicon              = "/favicon.ico"
    footerText           = "“Nothing Good Comes Easy”"
    homepage             = "Home"

[[params.mainMenu]]
    link = "/about"
    text = "About Mike"

[[params.mainMenu]]
    link = "https://www.linkedin.com/in/mike-graham/"
    text = "Mike on LinkedIn"

[[params.mainMenu]]
    link = "mailto:hello@mgrah.am"
    text = "Email Mike"
